# Generated by Django 3.1.7 on 2021-04-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210404_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.IngredientsForRecipe', to='recipes.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
