# Generated by Django 3.1.7 on 2021-04-07 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210407_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsforrecipe',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество'),
        ),
    ]
